Movie Page API
KrystianGreblowski/movies-browser pull request #28
Opened 2024-03-29 19:32 UTC by KrystianGreblowski

I have added data from API to MoviePage and I have also added many different things to make everything work well.

2024-04-01 19:22 UTC, Alekzann requested changes
It was a really great and excellent job! Unfortunately I can't appreciate the work with slice and saga, but the main thing is that it works! 
But, shadow in MoviePage in poster should be bigger, because when we have light image it's hard to see the movie title, crew should includes more persons.
Distance between MainInfo and Poster too big (as for me).

2024-04-01 19:22 UTC, Alekzann commented on src/features/MoviePage/Content/MainInfo/styled.js
Nice decision with grid, as you said previously! Good job!

2024-04-02 20:26 UTC, KrystianGreblowski commented
Thanks for the review. I changed the distance between MainInfo and Banner. I also changed the number of crew tiles. In my opinion, the box shadow is good enough and can't be bigger because it would take up too much space.

2024-04-03 22:19 UTC, Alekzann approved these changes
Great job!

2024-04-03 22:19 UTC, Alekzann commented on src/features/MoviePage/Banner/styled.js
> +  box-shadow: inset 0 0 100px 100px rgba(0, 0, 0);
What do you think about small changing of box-shadow from this to 
box-shadow: inset 0px 0px **150px 140px** rgba(0, 0, 0);
At least for bigger displays.

2024-04-04 15:04 UTC, closed without merging