Person details
KrystianGreblowski/movies-browser pull request #32
Opened 2024-04-05 15:46 UTC by Damian-Niklasinski

2024-04-06 21:41 UTC, Alekzann commented
Not bad, but it appears too raw for merging into the existing codebase. It seems that no changes were made based on my previous code review.

2024-04-08 16:51 UTC, Damian-Niklasinski commented
I have made the changes you wrote about, you can now see what the website looks like and let me know if everything is ok :)

2024-04-08 17:41 UTC, KrystianGreblowski commented on src/features/PersonDetails/styled.js
> +  max-width: 1920px;
I would change `max-width to 1400px`. The same max-width is in the MainPage, PersonList and MovieDetails.

I also added `padding: 0 16px` to gave some space between DetailsContainer and edge of screen

2024-04-08 17:46 UTC, KrystianGreblowski commented on src/features/PersonDetails/AboutPerson/styled.js
> +  margin-top: -226px;
I would delete `margin-top: -226px` because it makes some troubles on smaller screens. I would try to solve it in other way or you can keep it and change a value under breakpoints.

2024-04-08 17:49 UTC, KrystianGreblowski commented on src/features/PersonDetails/AboutPerson/styled.js
> +    grid-row: auto;
What do you think to add more breakpoints for PersonImage?
You could start adding smallLaptop breakpoint (1172px) and then tablet breakpoint etc.

2024-04-08 17:50 UTC, KrystianGreblowski commented on src/features/PersonDetails/AboutPerson/styled.js
> +    font-size: 16px;
As I comment for PersonImage, you could also change font-size for every styled-component which need it, for example: for Span, SpanInfo, Information etc.

2024-04-08 17:56 UTC, KrystianGreblowski requested changes
It looks much better than before but there's still some problems you could solve. I commented some lines of code, you can check it out. 

I think the main issue to solve is problem with PersonImage. I think you could add more breakpoints to change a size of image.

Btw. I see you have an old version of main, so when everything will be correct - be careful when you merge your pull-request

2024-04-08 19:04 UTC, Damian-Niklasinski commented
I added the changes you wrote above, I hope everything is okey now :)

2024-04-09 13:45 UTC, Alekzann commented
Better but not enough, 
1) container PersonDetails should be always on the top from mobile phones and lower;
2) birth details especially "Place of birth" shouldn't wrapping between 800px-768px and 700px-481px; 
3) PersonInformation looks better if it wrapping under the PersonImage and PersonDescription after 767px, because now we have to much empty space in the AboutPersonContainer and this don't looks good;
4) PersonDetails shouldn't go below the PersonImage after 480px;
5) Surface between PersonInformation and PersonImage shouldn't be so big;
**In each width our page should looks great not only in breakpoints.**

2024-04-09 13:48 UTC, Alekzann commented
Don't merge App.js folder with:
**//**import NoResults from "../features/NoResults";
**//**import MainPage from "../features/MainPage";
**//**import PersonList from "../features/PersonList";
**//**import { toMainPage, toPersonList } from "./routes";
**//**import MoviesDetails from "../features/MoviesDetails";

2024-04-09 17:13 UTC, Damian-Niklasinski commented
I added further corrections, unfortunately I don't know how to change the behavior of the page at the lowest resolutions, but I applied all the corrections you wrote about earlier.

2024-04-10 07:55 UTC, KrystianGreblowski approved these changes
That's good enough for now. I will merge it and then add api to this page and I will make some corrections if I see anything

2024-04-10 07:59 UTC, merged